#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "src/apu.h"

#define CPU_FREQ    1789773  // frequency of a NTCS CPU
#define SAMPLE_RATE 48000    // Audio sample rate
#define REGION      0        // 0:NTSC 1:PAL

/**
 * The following test suite was generated by Claude AI and reviewed by Will Morton.
 */

// Test result structure
typedef struct {
    const char* name;
    int passed;
    float sample_value;
} TestResult;

/**
 * @brief Helper function to tick APU multiple times and check for audio output
 */
float run_apu_for_samples(APU *apu, int num_ticks) {
    float max_sample = 0.0f;
    
    for (int i = 0; i < num_ticks; i++) {
        float sample = apu_tick(apu);
        if (sample > max_sample) {
            max_sample = sample;
        }
    }
    
    return max_sample;
}

/**
 * @brief Test 1: Pulse Channel 1 (440Hz A note)
 */
TestResult test_pulse1_440hz(APU *apu) {
    TestResult result = {"Pulse 1 @ 440Hz", 0, 0.0f};
    
    // Reset APU
    init_apu(apu, REGION);
    
    // Enable pulse 1
    apu_write(apu, 0x4015, 0x01);
    
    // Configure pulse 1 for 440Hz (A note)
    // Timer value = CPU_FREQ / (16 * desired_freq) - 1
    // For 440Hz: 1789773 / (16 * 440) - 1 ≈ 254
    apu_write(apu, 0x4000, 0xBF);  // 50% duty, constant volume, max volume (15)
    apu_write(apu, 0x4002, 0xFE);  // Timer low byte (254)
    apu_write(apu, 0x4003, 0x00);  // Timer high byte (0), length counter
    
    // Run for a few milliseconds worth of samples
    result.sample_value = run_apu_for_samples(apu, 10000);
    result.passed = (result.sample_value > 0.0f);
    
    return result;
}

/**
 * @brief Test 2: Pulse Channel 2 (880Hz A note, one octave up)
 */
TestResult test_pulse2_880hz(APU *apu) {
    TestResult result = {"Pulse 2 @ 880Hz", 0, 0.0f};
    
    init_apu(apu, REGION);
    
    // Enable pulse 2
    apu_write(apu, 0x4015, 0x02);
    
    // Configure pulse 2 for 880Hz
    // Timer value = 1789773 / (16 * 880) - 1 ≈ 126
    apu_write(apu, 0x4004, 0x7F);  // 25% duty, constant volume, max volume
    apu_write(apu, 0x4006, 0x7E);  // Timer low (126)
    apu_write(apu, 0x4007, 0x00);  // Timer high, length counter
    
    result.sample_value = run_apu_for_samples(apu, 10000);
    result.passed = (result.sample_value > 0.0f);
    
    return result;
}

/**
 * @brief Test 3: Both Pulse Channels (harmony)
 */
TestResult test_pulse_harmony(APU *apu) {
    TestResult result = {"Pulse Harmony (both channels)", 0, 0.0f};
    
    init_apu(apu, REGION);
    
    // Enable both pulse channels
    apu_write(apu, 0x4015, 0x03);
    
    // Pulse 1: 440Hz
    apu_write(apu, 0x4000, 0xBF);
    apu_write(apu, 0x4002, 0xFE);
    apu_write(apu, 0x4003, 0x00);
    
    // Pulse 2: 554Hz (C# note for harmony)
    // Timer = 1789773 / (16 * 554) - 1 ≈ 201
    apu_write(apu, 0x4004, 0x7F);
    apu_write(apu, 0x4006, 0xC9);  // 201
    apu_write(apu, 0x4007, 0x00);
    
    result.sample_value = run_apu_for_samples(apu, 10000);
    result.passed = (result.sample_value > 0.0f);
    
    return result;
}

/**
 * @brief Test 4: Triangle Channel
 */
TestResult test_triangle(APU *apu) {
    TestResult result = {"Triangle Wave", 0, 0.0f};
    
    init_apu(apu, REGION);
    
    // Enable triangle
    apu_write(apu, 0x4015, 0x04);
    
    // Configure triangle for ~440Hz
    // Triangle timer formula: CPU_FREQ / (32 * desired_freq) - 1
    // For 440Hz: 1789773 / (32 * 440) - 1 ≈ 126
    apu_write(apu, 0x4008, 0xFF);  // Control=1, linear counter reload = 127 (max)
    apu_write(apu, 0x400A, 0x7E);  // Timer low (126)
    apu_write(apu, 0x400B, 0x00);  // Timer high, length counter
    
    result.sample_value = run_apu_for_samples(apu, 10000);
    result.passed = (result.sample_value > 0.0f);
    
    return result;
}

/**
 * @brief Test 5: Noise Channel (white noise)
 */
TestResult test_noise_white(APU *apu) {
    TestResult result = {"Noise - White Noise", 0, 0.0f};
    
    init_apu(apu, REGION);
    
    // Enable noise
    apu_write(apu, 0x4015, 0x08);
    
    // Configure noise
    apu_write(apu, 0x400C, 0xBF);  // No length halt, constant volume, max volume (15)
    apu_write(apu, 0x400E, 0x05);  // Mode 0 (long LFSR), period 5 (moderate frequency)
    apu_write(apu, 0x400F, 0x00);  // Length counter load
    
    result.sample_value = run_apu_for_samples(apu, 10000);
    result.passed = (result.sample_value > 0.0f);
    
    return result;
}

/**
 * @brief Test 6: Noise Channel (tonal noise - short mode)
 */
TestResult test_noise_tonal(APU *apu) {
    TestResult result = {"Noise - Tonal (short LFSR)", 0, 0.0f};
    
    init_apu(apu, REGION);
    
    // Enable noise
    apu_write(apu, 0x4015, 0x08);
    
    // Configure noise with short LFSR (more tonal)
    apu_write(apu, 0x400C, 0xBF);  // Constant volume, max volume
    apu_write(apu, 0x400E, 0x88);  // Mode 1 (bit 7=1, short LFSR), period 8
    apu_write(apu, 0x400F, 0x00);  // Length counter
    
    result.sample_value = run_apu_for_samples(apu, 10000);
    result.passed = (result.sample_value > 0.0f);
    
    return result;
}

/**
 * @brief Test 7: All channels together
 */
TestResult test_all_channels(APU *apu) {
    TestResult result = {"All Channels Combined", 0, 0.0f};
    
    init_apu(apu, REGION);
    
    // Enable all channels (except DMC)
    apu_write(apu, 0x4015, 0x0F);
    
    // Pulse 1: 440Hz
    apu_write(apu, 0x4000, 0xBF);
    apu_write(apu, 0x4002, 0xFE);
    apu_write(apu, 0x4003, 0x00);
    
    // Pulse 2: 554Hz
    apu_write(apu, 0x4004, 0x7F);
    apu_write(apu, 0x4006, 0xC9);
    apu_write(apu, 0x4007, 0x00);
    
    // Triangle: 220Hz (bass)
    apu_write(apu, 0x4008, 0xFF);
    apu_write(apu, 0x400A, 0xFC);  // ~220Hz
    apu_write(apu, 0x400B, 0x00);
    
    // Noise: percussion
    apu_write(apu, 0x400C, 0x9F);  // Lower volume (10)
    apu_write(apu, 0x400E, 0x03);
    apu_write(apu, 0x400F, 0x00);
    
    result.sample_value = run_apu_for_samples(apu, 10000);
    result.passed = (result.sample_value > 0.0f);
    
    return result;
}

/**
 * @brief Test 8: Envelope test (volume fade)
 */
TestResult test_envelope(APU *apu) {
    TestResult result = {"Envelope (volume decay)", 0, 0.0f};
    
    init_apu(apu, REGION);
    
    // Enable pulse 1
    apu_write(apu, 0x4015, 0x01);
    
    // Configure with envelope (NOT constant volume)
    apu_write(apu, 0x4000, 0xAF);  // duty=2, length_halt=1, envelope mode
    apu_write(apu, 0x4002, 0xFE);
    apu_write(apu, 0x4003, 0x00);
    
    // Run for enough frames to see envelope decay
    result.sample_value = run_apu_for_samples(apu, 30000);
    result.passed = (result.sample_value > 0.0f);
    
    return result;
}

/**
 * @brief Test 9: Status register read
 */
TestResult test_status_read(APU *apu) {
    TestResult result = {"Status Register Read", 0, 0.0f};
    
    init_apu(apu, REGION);
    
    // Enable all channels
    apu_write(apu, 0x4015, 0x0F);
    
    // Configure channels with length counters
    apu_write(apu, 0x4003, 0x08);  // Pulse 1 length
    apu_write(apu, 0x4007, 0x08);  // Pulse 2 length
    apu_write(apu, 0x400B, 0x08);  // Triangle length
    apu_write(apu, 0x400F, 0x08);  // Noise length
    
    // Read status
    uint8_t status = apu_read(apu, 0x4015);
    
    // Should have bits 0-3 set (all length counters > 0)
    result.passed = ((status & 0x0F) == 0x0F);
    result.sample_value = (float)status;
    
    return result;
}

/**
 * @brief Test 10: Sweep unit test
 */
TestResult test_sweep(APU *apu) {
    TestResult result = {"Sweep Unit", 0, 0.0f};
    
    init_apu(apu, REGION);
    
    // Enable pulse 1
    apu_write(apu, 0x4015, 0x01);
    
    // Configure with sweep enabled
    apu_write(apu, 0x4000, 0xBF);  // Max volume
    apu_write(apu, 0x4001, 0x89);  // Sweep: enabled, period=1, negate=0, shift=0
    apu_write(apu, 0x4002, 0x00);  // Timer = 512 (start frequency)
    apu_write(apu, 0x4003, 0x02);
    
    // Run long enough for sweep to take effect
    result.sample_value = run_apu_for_samples(apu, 50000);
    result.passed = (result.sample_value > 0.0f);
    
    return result;
}

/**
 * @brief Print test results
 */
void print_test_results(TestResult *results, int num_tests) {
    printf("\n");
    printf("================================================================\n");
    printf("              NES APU Test Suite Results                       \n");
    printf("================================================================\n");
    
    int passed = 0;
    for (int i = 0; i < num_tests; i++) {
        const char *status = results[i].passed ? "[PASS]" : "[FAIL]";
        printf("  %-6s %-35s | %.4f\n", 
               status, results[i].name, results[i].sample_value);
        if (results[i].passed) passed++;
    }
    
    printf("================================================================\n");
    printf("  Tests Passed: %2d / %2d\n", passed, num_tests);
    printf("================================================================\n");
    printf("\n");
}

/**
 * @brief Main test runner
 */
int main() {
    APU apu;
    TestResult results[10];
    
    printf("NES APU Test Suite Starting...\n");
    printf("Region: %s\n", REGION == NTSC ? "NTSC" : "PAL");
    printf("Sample Rate: %d Hz\n\n", SAMPLE_RATE);
    
    // Run all tests
    results[0] = test_pulse1_440hz(&apu);
    results[1] = test_pulse2_880hz(&apu);
    results[2] = test_pulse_harmony(&apu);
    results[3] = test_triangle(&apu);
    results[4] = test_noise_white(&apu);
    results[5] = test_noise_tonal(&apu);
    results[6] = test_all_channels(&apu);
    results[7] = test_envelope(&apu);
    results[8] = test_status_read(&apu);
    results[9] = test_sweep(&apu);
    
    // Print results
    print_test_results(results, 10);
    
    // Overall result
    int total_passed = 0;
    for (int i = 0; i < 10; i++) {
        if (results[i].passed) total_passed++;
    }
    
    if (total_passed == 10) {
        printf("All tests passed!\n");
        return 0;
    } else {
        printf("Some tests failed.\n");
        return 1;
    }
}
