#include "apu.h"

/*
 * TODO:
 *   [X]  Implement Required Static Tables
 *   [ ]  Implement Pulse Wave Generators
 *   [ ]  Implement Triangle Wave Generators
 *   [ ]  Implement Noise Wave Generator
 *   [ ]  Set up APU and channel init
 *   [ ]  Correctly output audio to SDL2 Interface
 *   [ ]  Implement DMC Channel
 */

// pulse sequencer duty cycle sequences
static uint8_t duty[4][8] = {
    {0, 1, 0, 0, 0, 0, 0, 0},
    {0, 1, 1, 0, 0, 0, 0, 0},
    {0, 1, 1, 1, 1, 0, 0, 0},
    {1, 0, 0, 1, 1, 1, 1, 1}
};

/** 
 * @brief length counter table for both NTSC and PAL
 * 
 * A table full of note length values. Counter counts down at ~240hz for 
 * these lengths.
 * 
 * Used by Pulse, Triangle, Noise
 */
static const uint8_t length_table[32] = {
    10, 254, 20,  2, 40,  4, 80,  6,
    160,  8, 60, 10, 14, 12, 26, 14,
    12,  16, 24, 18, 48, 20, 96, 22,
    192, 24, 72, 26, 16, 28, 32, 30
};

/**
 * @brief Noise period tables for both NTSC and PAL
 * 
 * Tables denoting how fast the noise Linear Feedback Shift Register (LFSR) 
 * shifts. Noise is generated by LFSR and tells the APU how often to shift it. 
 * 
 * Each value is the number of CPU cycles between shifts.
 */
static const uint16_t noise_period_ntsc[16] = {
      4,   8,  16,  32,  64,   96,  128,  160,
    202, 254, 380, 508, 762, 1016, 2034, 4068
};
static const uint16_t noise_period_pal[16] = {
      4,   8,  16,  32,  64,  80,   96,  112,
    126, 160, 202, 254, 380, 508, 1016, 2034
};

/**
 * @brief Delta Modulation Channel rate tables for both NTSC and PAL
 * 
 * Tables store hardcoded values for how fast a sample playback advances. This 
 * table tells the APU how fast to fetch the next bit.
 */
static const uint16_t dmc_rate_ntsc[16] = {
    428, 380, 340, 320, 286, 254, 226, 214,
    190, 160, 142, 128, 106,  85,  72,  54
};
static const uint16_t dmc_rate_pal[16] = {
    398, 354, 316, 298, 276, 236, 210, 198,
    176, 148, 132, 118,  98,  78,  66,  50
};

// function headers
Pulse init_pulse(int id);
Triangle init_triangle();
Noise init_noise();
Delta init_dmc();

/**
 * @brief Initialize APU and create sound channels
 * 
 * Initializes the APU with the correct region and safe initial values.
 */
void init_apu(APU *apu, Region region) {
    // set appropriate region
    apu->region = region;
    
    // initialize registers
    for (int i = 0; i < 4; i++) {
        apu->registers.pulse1[i] = 0;
        apu->registers.pulse2[i] = 0;
        apu->registers.triangle[i] = 0;
        apu->registers.noise[i] = 0;
        apu->registers.dmc[i] = 0;
    }
    apu->registers.status = 0;
    apu->registers.frame_counter = 0;

    // set cycle to 0
    apu->cycles = 0;

    // initialize sound channels
    apu->pulse1 = init_pulse(1);
    apu->pulse2 = init_pulse(2);
    // apu->triangle = init_triangle();
    // apu->noise = init_noise();
    // apu->dmc = init_dmc();
}

Pulse init_pulse(int id) {
    Pulse pulse;
    
    pulse.id = id;

    pulse.duty_cycle = 0;
    pulse.length_halt = 0;
    pulse.constant_volume = 0;
    pulse.envelope_volume = 0;

    pulse.sweep_enabled = 0;
    pulse.sweep_period = 0;
    pulse.sweep_negate = 0;
    pulse.sweep_shift = 0;

    pulse.timer_reload = 0;
    pulse.timer_counter = 0;
    pulse.seq_pos = 0;
    pulse.length_counter = 0;

    return pulse;
}

// future todo
Triangle init_triangle() {}
Noise init_noise() {}
Delta init_dmc() {}

/**
 * @brief Advances the pulse channel by one CPU cycle
 * 
 * It updates the internal timer for the pulse channel.
 * If the timer reaches 0, it reloads from the timer reload and advances the
 * waveform sequence by one step. Otherwise decrement.
 */
void pulse_tick(Pulse *p) {
    if (p->timer_counter == 0) {
        p->timer_counter = p->timer_reload;
        p->seq_pos = (p->seq_pos + 1) & 7;
    } else {
        p->timer_counter--;
    }
}

/**
 * @brief Amplitude output function
 * 
 * Checks if the note should be playing and calculates output based on the duty sequence.
 */
uint8_t pulse_output(Pulse *p) {
    if (p->length_counter == 0) return 0;
    return duty[p->duty_cycle][p->seq_pos] ? p->envelope_volume : 0;
}
